### ISSUE TITLE
Install fails on MacOS (Intel)

### ISSUE THREAD

**Issue by tautf** [julianhille/MuhammaraJS#242] opened 2022-12-05 13:53 UTC
After updating several version i'm not able to install muhammara anymore:

```
npm ERR! path /Users/tauthot/Documents/Dev.nosync/heat-coat/app/webserver/node_modules/muhammara
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@16.18.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/tauthot/Documents/Dev.nosync/heat-coat/app/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/tauthot/Documents/Dev.nosync/heat-coat/app/webserver/node_modules/muhammara/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/tauthot/Documents/Dev.nosync/heat-coat/app/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/tauthot/Library/Caches/node-gyp/16.18.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/tauthot/Library/Caches/node-gyp/16.18.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/tauthot/Documents/Dev.nosync/heat-coat/app/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/tauthot/Library/Caches/node-gyp/16.18.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/tauthot/Documents/Dev.nosync/heat-coat/app/webserver/node_modules/muhammara',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/tauthot/Documents/Dev.nosync/heat-coat/app/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/Users/tauthot/.nvm/versions/node/v16.18.1/bin/node" "/Users/tauthot/Documents/Dev.nosync/heat-coat/app/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/tauthot/Documents/Dev.nosync/heat-coat/app/webserver/node_modules/muhammara
npm ERR! gyp ERR! node -v v16.18.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok
```

**Comment by julianhille** [comment] 2022-12-05 14:17
please try `node-pre-gyp build` instead of node-gyp.

**Comment by julianhille** [comment] 2022-12-07 08:24
btw im curious why are you compiling? What prebuilt or else is missing that you can't use the prebuilt downloads?

**Comment by tautf** [comment] 2022-12-07 08:40
I do not manually do that. I simply ran `npm install` in my repo and this is the output.

**Comment by julianhille** [comment] 2022-12-07 08:44
interesting. i've never encountered such behavior. are you able to give a minimal example to reproduce?

So far i see:
- macOS intel
- node 16.18.1
- node-gyp 9.3.0

What i would like to know too:
- muhammara version
- npm version

**Comment by tautf** [comment] 2022-12-07 08:46
> interesting. i've never encountered such behavior. are you able to give a minimal example to reproduce?
> 
> So far i see:
> 
> * macOS intel
> * node 16.18.1
> * node-gyp 9.3.0
> 
> What i would like to know too:

 * muhammara version -> packag.json entry: `"muhammara": "^3.2.0",`
 * npm version -> 8.19.2

**Comment by julianhille** [comment] 2022-12-07 08:49
and what version is used in package-lock or yarn.lock of muhammara?

can you extract all parts of muhammara from the package lock file please, so i can see what it is trying to download.

**Comment by julianhille** [comment] 2022-12-13 07:32
Any updates on this? some module/command thinks that node-gyp needs to be issued with `rebuild` subcommand which does not work directly.

**Comment by tautf** [comment] 2022-12-14 09:19
> and what version is used in package-lock or yarn.lock of muhammara?
> 
> can you extract all parts of muhammara from the package lock file please, so i can see what it is trying to download.

Sorry for the late response.
This error only appears if i delete my package-lock.json so he doens't have the matched versions cached.

Not sure if this is really an issue but i would recommend to retry this.

Delete your package-lock.json, run `npm install`

**Comment by julianhille** [comment] 2022-12-14 09:54
interesting, i can not reproduce this. will try several things.

**Comment by julianhille** [comment] 2023-01-24 11:06
I'm still unable to reproduce. I'll close it until someone can dig a bit deeper or also encounters this issue.

Feel free to reopen.

**Closed as completed by julianhille** 2023-01-24 11:06 UTC
Labels: question
